modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="recipestages" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Recipe Stages" #mandatory
authors="Jaredlll08" #optional
description='''
'''